app = "mets-hrs"
primary_region = "ewr"

[build]

[env]
  POLL_INTERVAL = "30"
  LOG_LEVEL = "INFO"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
