name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy-discloud:
    name: Deploy to Discloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: discloud/github-action@v2
        with:
          token: ${{ secrets.DISCLOUD_TOKEN }}

  deploy-fly:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
